--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/CTMCentral/libDockerHandler
build-by-default: true
projects:
  libDockerHandler:
    path: ""
    model: virion
    type: library
...
